<?php

include __DIR__ . '/autoloadClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-13 at 13:12:34.
 */
class CoreCommodityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CoreCommodity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CoreCommodity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('a', 10, 'aaa') == true.
     *
     * @covers CoreCommodity::addCommodity
     */
    public function testAddCommodity() {
        $this->assertEquals(
                true
                , $this->object->addCommodity('a', 10, 'aaa')
        );
    }

    /**
     * Generated from @assert ('a') == true.
     *
     * @covers CoreCommodity::deleteCommodity
     */
    public function testDeleteCommodity() {
        $this->assertEquals(
                true
                , $this->object->deleteCommodity('a')
        );
    }

    /**
     * Generated from @assert ('b') == false.
     *
     * @covers CoreCommodity::deleteCommodity
     */
    public function testDeleteCommodity2() {
        $this->assertEquals(
                false
                , $this->object->deleteCommodity('b')
        );
    }

    /**
     * @covers CoreCommodity::getCommodities
     * @todo   Implement testGetCommodities().
     */
    public function testGetCommodities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
