<?php

include __DIR__ . '/autoloadClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-13 at 13:05:05.
 */
class CoreUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CoreUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CoreUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('a', 'a') == true.
     *
     * @covers CoreUser::login
     */
    public function testLogin() {
        $this->assertEquals(
                true
                , $this->object->login('a', 'a')
        );
    }

    /**
     * Generated from @assert ('a', 'b') == false.
     *
     * @covers CoreUser::login
     */
    public function testLogin2() {
        $this->assertEquals(
                false
                , $this->object->login('a', 'b')
        );
    }

    /**
     * Generated from @assert ('b', 'b') == true.
     *
     * @covers CoreUser::addUser
     */
    public function testAddUser() {
        $this->assertEquals(
                true
                , $this->object->addUser('b', 'b')
        );
    }

    /**
     * Generated from @assert ('c', 'c') == true.
     *
     * @covers CoreUser::addUser
     */
    public function testAddUser2() {
        $this->assertEquals(
                true
                , $this->object->addUser('c', 'c')
        );
    }

    /**
     * Generated from @assert ('b') == true.
     *
     * @covers CoreUser::deleteUser
     */
    public function testDeleteUser() {
        $this->assertEquals(
                true
                , $this->object->deleteUser('b')
        );
    }

    /**
     * Generated from @assert ('c') == true.
     *
     * @covers CoreUser::deleteUser
     */
    public function testDeleteUser2() {
        $this->assertEquals(
                true
                , $this->object->deleteUser('c')
        );
    }

    /**
     * Generated from @assert ('d') == false.
     *
     * @covers CoreUser::deleteUser
     */
    public function testDeleteUser3() {
        $this->assertEquals(
                false
                , $this->object->deleteUser('d')
        );
    }

    /**
     * @covers CoreUser::checkLogin
     * @todo   Implement testCheckLogin().
     */
    public function testCheckLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CoreUser::createSalt
     * @todo   Implement testCreateSalt().
     */
    public function testCreateSalt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
