<?php

include __DIR__ . '/autoloadClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-14 at 14:00:36.
 */
class CoreNoticeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CoreNotice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CoreNotice;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('haha') == true.
     *
     * @covers CoreNotice::changeNotice
     */
    public function testChangeNotice() {
        $this->assertEquals(
                true
                , $this->object->changeNotice('haha')
        );
    }

    /**
     * Generated from @assert ('hehe') == true.
     *
     * @covers CoreNotice::changeNotice
     */
    public function testChangeNotice2() {
        $this->assertEquals(
                true
                , $this->object->changeNotice('hehe')
        );
    }

    /**
     * @covers CoreNotice::getNotice
     * @todo   Implement testGetNotice().
     */
    public function testGetNotice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
